version: '3.11'


services:
  bot:
    build: .
    restart: always
    container_name: FitNice_bot_by_me
    environment:
      TOKEN: 7037879367:AAG0ISCCehaD3XKZT8K6Ka7D0Rk-w14gS_0
      DB_USER: postgres
      DB_NAME: postgres
      DB_HOST: pg
      DB_PORT: 5432
      DB_PASSWORD: 1

    depends_on:
      - pg


  pg:
    image: postgres:alpine
    restart: always
    container_name: pg_con
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: